server.port=8000
spring.application.name=Data Subject Request
spring.datasource.url=jdbc:mysql://localhost:3307/iit_msc_final_project?useSSL=false
spring.datasource.username=root
spring.datasource.password=20030909
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sisukaweerasinghe@gmail.com
spring.mail.password=rxnutcogjdvvpqeh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true